Repository UBCSailbot/sailbot_workspace, pull requests merged in 2022-11, with the labels that each got.

#49 Add CODEOWNERS
  .github/CODEOWNERS
Labels: infrastructure

#50 Update CODEOWNERS
  .github/CODEOWNERS
Labels: ignore-for-release, infrastructure

#47 Add C++ dependencies and configuration files
  .clang-format
  .clang-tidy
  .devcontainer/Dockerfile
  .devcontainer/config/sailbot_workspace.code-workspace
  .devcontainer/dev/Dockerfile
  .devcontainer/devcontainer.json
  .github/actions/lint/run.sh
  .github/actions/test/run.sh
  .github/workflows/lint.yaml
  .gitignore
  .vscode/c_cpp_properties.json
  build.sh
  run_clang-tidy.sh
  src/new_project.repos
Labels: infrastructure, devcontainer, workflows

#53 Ignore distrowatch links
  .markdown-link-check.json
Labels: bug, infrastructure

#48 Automate Windows 10 x11 forwarding
  .devcontainer/devcontainer.json
  README.md
Labels: bug, infrastructure, devcontainer

#59 Migrate README to docs site
  .github/workflows/lint.yaml
  README.md
Labels: documentation

#60 Update Scripts to Migrate CI to Subteam Repos
  .github/actions/lint/run.sh
  .github/actions/test/run.sh
  .github/workflows/readme-lint.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/test.yaml
  README.md
  setup.sh
Labels: infrastructure
