Repository UBCSailbot/sailbot_workspace, pull requests merged in 2022-10, with the labels that each got.

#32 Create workspace file
  .devcontainer/.dockerignore
  .devcontainer/Dockerfile
  .devcontainer/config/README.md
  .devcontainer/config/sailbot_workspace.code-workspace
  .devcontainer/dev/Dockerfile
  .gitignore
  README.md
Labels: bug, documentation, infrastructure

#41 Migrate VS Code configuration and revamp CI
  .devcontainer/config/sailbot_workspace.code-workspace
  .github/workflows/lint.yaml
  .github/workflows/ros-lint-and-test.yaml
  .github/workflows/test.yaml
  .vscode/cspell.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  README.md
Labels: infrastructure

#42 Fix create new package with a node tasks
  .devcontainer/config/sailbot_workspace.code-workspace
Labels: bug, infrastructure

#44 Create Docker volume for ROS 1 workspace
  .devcontainer/devcontainer.json
Labels: infrastructure, devcontainer

#34 Fix x11 forwarding and revamp setup instructions
  .devcontainer/README.md
  .devcontainer/dev/README.md
  .devcontainer/devcontainer.json
  README.md
Labels: bug, documentation, infrastructure

#46 Update VS Code extensions
  .devcontainer/config/sailbot_workspace.code-workspace
  .devcontainer/devcontainer.json
Labels: infrastructure
