Repository UBCSailbot/sailbot_workspace, pull requests merged in 2023-12, with the labels that each got.

#217 Support multiple global launch configs
  src/global_launch/main_launch.py
Labels: infrastructure

#218 Update markdown linters
  .github/workflows/test_definitions.yml
  .markdown-link-check.json
  .markdownlint.json
Labels: github, infrastructure

#219 Run extract-metadata job when needed
  .github/workflows/test_definitions.yml
Labels: bug, github, infrastructure

#220 VS Code Infrastructure Update
  .devcontainer/devcontainer.json
  sailbot.code-workspace
Labels: vscode, infrastructure

#221 Addition of Global Parameters for Mock Global Path Node
  src/global_launch/config/README.md
  src/global_launch/config/globals.yaml
Labels: infrastructure
