Repository UBCSailbot/sailbot_workspace, pull requests merged in 2023-06, with the labels that each got.

#130 Add local pathfinding repo and improve python infra
  .devcontainer/Dockerfile
  .devcontainer/base-dev/base-dev.Dockerfile
  .devcontainer/config/sailbot_workspace.code-workspace
  .devcontainer/devcontainer.json
  .github/workflows/test_definitions.yml
  .github/workflows/tests.yml
  setup.sh
  src/new_project.repos
Labels: vscode, infrastructure

#131 Add raye-local-pathfinding repo to workspace
  .devcontainer/config/sailbot_workspace.code-workspace
  .github/actions/ament-lint/run.sh
  src/new_project.repos
Labels: infrastructure

#132 Update VS Code configuration
  .devcontainer/config/sailbot_workspace.code-workspace
  .devcontainer/devcontainer.json
Labels: vscode, infrastructure

#133 Skip existing directories when setting up
  setup.sh
Labels: vscode, infrastructure

#134 Improve Python testing infrastructure
  .devcontainer/Dockerfile
  .devcontainer/config/sailbot_workspace.code-workspace
  test.sh
Labels: vscode, infrastructure

#129 Add more workflow input arguments and fix linting workflow
  .github/actions/ament-lint/run.sh
  .github/workflows/test_definitions.yml
  .github/workflows/tests.yml
  run_clang-tidy.sh
Labels: github, infrastructure

#114 Add Boat Simulator and Enhance Build Tasks
  .devcontainer/config/sailbot_workspace.code-workspace
  .github/workflows/test_definitions.yml
  .github/workflows/tests.yml
  build.sh
  quick_build.sh
  src/new_project.repos
Labels: enhancement, infrastructure

#135 Improve debugging experience
  .devcontainer/config/sailbot_workspace.code-workspace
  .devcontainer/devcontainer.json
Labels: vscode, infrastructure

#136 Update documentation for v1.2.0 release
  .devcontainer/deployment/README.md
  README.md
Labels: documentation

#137 Fix rebuild docs
  .github/workflows/test_definitions.yml
Labels: bug, infrastructure

#139 Link to how to run Raye's software
  README.md
Labels: documentation

#140 Source ROS underlay if overlay not found
  .devcontainer/Dockerfile
  .devcontainer/base-dev/update-bashrc.sh
Labels: bug, devcontainer, infrastructure

#141 Update ROS sourcing
  .devcontainer/Dockerfile
  .devcontainer/base-dev/update-bashrc.sh
Labels: devcontainer, infrastructure

#143 Migrate MongoDB CLI to local-base image
  .devcontainer/Dockerfile
  .devcontainer/base-dev/base-dev.Dockerfile
  .devcontainer/website/website.Dockerfile
Labels: bug, infrastructure

#144 Add Pylance extension
  .devcontainer/config/sailbot_workspace.code-workspace
  .devcontainer/devcontainer.json
Labels: vscode, infrastructure

#145 Fix VCS enabled in other repositories
  .github/workflows/test_definitions.yml
Labels: bug, github, infrastructure

#147 Remove references to old custom interfaces branch and change to main
  .github/workflows/test_definitions.yml
Labels: bug, github, infrastructure

#150 Fix redundant custom interfaces
  .github/workflows/test_definitions.yml
Labels: bug, github, infrastructure

#151 Revert setup skipping existing repositories
  setup.sh
Labels: infrastructure
