Repository UBCSailbot/sailbot_workspace, pull requests merged in 2023-09, with the labels that each got.

#58 Add C++ unit testing
  .devcontainer/config/sailbot_workspace.code-workspace
  .devcontainer/devcontainer.json
Labels: vscode, infrastructure

#162 Fix C++ debug config
  .devcontainer/config/sailbot_workspace.code-workspace
Labels: bug

#168 Revert "Revert setup skipping existing repositories"
  .devcontainer/config/sailbot_workspace.code-workspace
  .github/actions/ament-lint/run.sh
  .gitignore
  setup.sh
  src/polaris.repos
Labels: infrastructure

#169 Add controller repository
  .devcontainer/config/sailbot_workspace.code-workspace
  src/polaris.repos
Labels: infrastructure
