Repository UBCSailbot/sailbot_workspace, pull requests merged in 2023-07, with the labels that each got.

#153 Maker user owner of dotfiles
  .devcontainer/Dockerfile
Labels: bug, infrastructure

#155 Specify interpreter path for python extensions
  .devcontainer/config/sailbot_workspace.code-workspace
Labels: bug, vscode

#158 Format all Python strings to be double quotes
  .devcontainer/config/sailbot_workspace.code-workspace
Labels: vscode, infrastructure
