Repository UBCSailbot/sailbot_workspace, pull requests merged in 2024-04, with the labels that each got.

#349 Add Eric to CODEOWNERS
  .github/CODEOWNERS
Labels: infrastructure

#351 Update docs site infrastructure
  .devcontainer/docs/docs.Dockerfile
  .github/workflows/docs.yml
  docs/requirements.txt
Labels: infrastructure

#346 [WEB] DATA FOR RESEARCHERS
  src/website/package-lock.json
  src/website/package.json
  src/website/pages/Polaris/index.tsx
  src/website/pages/index.tsx
  src/website/pages/style.module.css
  src/website/public/Polaris.png
  src/website/utils/DownloadData.tsx
  src/website/views/DashboardContainer.tsx
  src/website/views/MapsContainer.tsx
  src/website/views/components/BoatCompass/BoatCompass.tsx
  src/website/views/components/BoatCompass/boatcompass.module.css
  src/website/views/components/DropDown/DropDown.module.css
  src/website/views/components/DropDown/DropDown.tsx
  src/website/views/components/Header/Header.tsx
  src/website/views/components/Header/header.module.css
  src/website/views/components/LineChart/UPlotLineChart.tsx
  src/website/views/components/LineChart/UPlotMultiLineChart.tsx
  src/website/views/components/Polaris/PolarisContainer.module.css
  src/website/views/components/Polaris/PolarisContainer.tsx
  src/website/views/components/SingleValueChart/SingleValueChart.tsx
  src/website/views/components/SingleValueChart/singlevaluechart.module.css
  src/website/views/components/SingleValueLine/SingleValueLine.tsx
  src/website/views/components/SingleValueLine/singlevalueline.module.css
Labels: web

#320 Implement controllers for rudder and sail actuation mechanisms
  src/boat_simulator/boat_simulator/common/constants.py
  src/boat_simulator/boat_simulator/nodes/low_level_control/control.py
  src/boat_simulator/boat_simulator/nodes/low_level_control/controller.py
  src/boat_simulator/tests/unit/common/test_generators.py
  src/boat_simulator/tests/unit/nodes/low_level_control/test_control.py
  src/boat_simulator/tests/unit/nodes/low_level_control/test_controller.py
Labels: sim

#354 Combine docs-deploy and docs-delete jobs
  .github/workflows/docs.yml
Labels: bug, infrastructure

#355 Add back pushing deleting docs version
  .github/workflows/docs.yml
Labels: bug, infrastructure

#356 Another attempt to resolve docs-update push conflicts
  .github/workflows/docs.yml
Labels: bug, infrastructure

#357 Hopefully this actually fixes docs-update push conflicts
  .github/workflows/docs.yml
Labels: bug, infrastructure

#358 Authenticate inside container for docs-update
  .github/workflows/docs.yml
Labels: bug, infrastructure

#359 Change authentication method
  .github/workflows/docs.yml
Labels: bug, infrastructure

#360 Wait for docs to deploy before deleting
  .github/workflows/docs.yml
Labels: bug, infrastructure

#364 Miscellaneous infrastructure updates
  .devcontainer/base-dev/update-bashrc.sh
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/docs/docker-compose.docs.yml
  .devcontainer/website/docker-compose.website.yml
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/create-tasklist.md
  .github/ISSUE_TEMPLATE/docs-page-new.md
  .github/ISSUE_TEMPLATE/docs-page-update.md
  .github/ISSUE_TEMPLATE/feature-new.md
  .github/ISSUE_TEMPLATE/feature-update.md
  .github/ISSUE_TEMPLATE/infrastructure-update.md
  .github/actions/run-in-container/action.yml
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/docs.yml
  .markdownlintignore
  docs/current/docs/overview.md
  docs/current/sailbot_workspace/setup.md
  docs/reference/github/workflow/branches.md
  sailbot.code-workspace
Labels: infrastructure

#365 Changed Port for Posting Global Paths in Tests
  src/local_pathfinding/local_pathfinding/global_path.py
  src/local_pathfinding/test/post_server.py
  src/local_pathfinding/test/test_global_path.py
Labels: bug, path
