Repository UBCSailbot/sailbot_workspace, pull requests merged in 2024-05, with the labels that each got.

#366 CD for Website
  .devcontainer/website/docker-compose.website.prod.yml
  .devcontainer/website/website.Dockerfile.prod
  .github/workflows/deployment.yml
  src/website/.env.development
  src/website/.env.production
  src/website/lib/dotenv.js
  src/website/models/helper/parser.js
  src/website/package-lock.json
  src/website/package.json
  src/website/stores/AISShips/AISShipsReducers.ts
  src/website/stores/AISShips/AISShipsSagas.ts
  src/website/stores/AISShips/AISShipsTypes.ts
  src/website/stores/Batteries/BatteriesReducers.ts
  src/website/stores/Batteries/BatteriesSagas.ts
  src/website/stores/Batteries/BatteriesTypes.ts
  src/website/stores/DataFilter/DataFilterSagas.ts
  src/website/stores/GPS/GPSSagas.ts
  src/website/stores/GPS/GPSTypes.ts
  src/website/stores/GenericSensors/GenericSensorsReducers.ts
  src/website/stores/GenericSensors/GenericSensorsSagas.ts
  src/website/stores/GenericSensors/GenericSensorsTypes.ts
  src/website/stores/GlobalPath/GlobalPathReducers.ts
  src/website/stores/GlobalPath/GlobalPathSagas.ts
  src/website/stores/GlobalPath/GlobalPathTypes.ts
  src/website/stores/Graphs/GraphsSagas.ts
  src/website/stores/LocalPath/LocalPathReducers.ts
  src/website/stores/LocalPath/LocalPathSagas.ts
  src/website/stores/LocalPath/LocalPathTypes.ts
  src/website/stores/WindSensors/WindSensorsReducers.ts
  src/website/stores/WindSensors/WindSensorsSagas.ts
  src/website/stores/WindSensors/WindSensorsTypes.ts
  src/website/tests/shared/classes/api.ts
  src/website/tests/shared/classes/response-error.ts
  src/website/tsconfig.json
  src/website/utils/DownloadData.js
  src/website/views/DashboardContainer.tsx
  src/website/views/MapsContainer.tsx
  src/website/views/components/BoatCompass/BoatCompass.tsx
  src/website/views/components/Dataset/Dataset.tsx
  src/website/views/components/DropDown/DropdownMenu.tsx
  src/website/views/components/LineChart/UPlotLineChart.tsx
  src/website/views/components/LineChart/UPlotMultiLineChart.tsx
  src/website/views/components/Polaris/PolarisContainer.tsx
  src/website/views/components/TimestampFilter/TimestampBtn.tsx
  src/website/views/components/TimestampFilter/TimestampFilter.tsx
  src/website/views/components/checkbox/Checkboxes.tsx
Labels: infrastructure

#386 Update Website README
  .github/CODEOWNERS
  src/website/README.md
Labels: web

#361 Reorganize Shell Scripts
  .devcontainer/base-dev/README.md
  .devcontainer/devcontainer.json
  .github/actions/action.yml
  .github/actions/run-in-container/clang-tidy.sh
  .github/actions/run-in-container/test.sh
  .github/workflows/tests.yml
  .markdown-link-check.json
  docs/current/sailbot_workspace/deployment.md
  docs/current/sailbot_workspace/scripts.md
  mkdocs.yml
  sailbot.code-workspace
  scripts/README.md
  scripts/ament-lint.sh
  scripts/ament_clang_tidy.py
  scripts/build.sh
  scripts/clang-tidy.sh
  scripts/deployment/README.md
  scripts/deployment/helpers/setup_can.sh
  scripts/deployment/setup_boot.sh
  scripts/deployment/start_container.sh
  scripts/run-tests.sh
  scripts/run_virtual_iridium.sh
  scripts/setup.sh
  scripts/test.sh
  src/integration_tests/integration_tests/integration_test_node.py
  src/network_systems/README.md
  src/network_systems/projects/local_transceiver/CMakeLists.txt
  src/network_systems/projects/local_transceiver/test/test_local_transceiver.cpp
  src/network_systems/projects/remote_transceiver/inc/remote_transceiver.h
  src/network_systems/scripts/README.md
  src/network_systems/scripts/run_virtual_iridium.sh
Labels: infrastructure

#374 Miscellaneous Docs Site Updates
  .github/workflows/docs.yml
  docs/about_us.md
  docs/current/docs/overview.md
  docs/current/sailbot_workspace/overview.md
  docs/current/sailbot_workspace/reference/deployment.md
  docs/current/sailbot_workspace/reference/docker_images.md
  docs/current/sailbot_workspace/reference/docs_site.md
  docs/current/sailbot_workspace/reference/launch_files.md
  docs/current/sailbot_workspace/reference/parameters.md
  docs/current/sailbot_workspace/usage/help.md
  docs/current/sailbot_workspace/usage/how_to.md
  docs/current/sailbot_workspace/usage/setup.md
  docs/current/sailbot_workspace/usage/workflow.md
  docs/index.md
  docs/reference/docker.md
  docs/reference/github/advanced_git.md
  docs/reference/github/github_actions.md
  docs/reference/github/workflow/overview.md
  docs/reference/linux_commands.md
  docs/reference/markdown.md
  docs/reference/ros.md
  docs/reference/sailing/overview.md
  docs/requirements.txt
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: docs

#388 Make new leads codeowners
  .github/CODEOWNERS
Labels: infrastructure

#389 Move notebooks documentation to sailbot workspace reference
  docs/current/sailbot_workspace/reference/notebooks.md
  mkdocs.yml
  src/boat_simulator/README.md
Labels: docs

#390 Add website/tests/node_modules and settings.json to .gitignore
  .gitignore
Labels: bug, web, infrastructure
