Repository UBCSailbot/sailbot_workspace, pull requests merged in 2024-01, with the labels that each got.

#225 Enable VCS in custom_interfaces CI
  .github/workflows/test_definitions.yml
Labels: github, infrastructure

#226 Markdown linter configuration fixes
  .markdown-link-check.json
  .markdownlint.json
Labels: github, infrastructure

#223 Added a write parameter for the Mock Global Path node
  src/global_launch/config/README.md
  src/global_launch/config/globals.yaml
Labels: infrastructure

#224 Integration Test Framework
  .devcontainer/Dockerfile
  .devcontainer/base-dev/base-dev.Dockerfile
  .gitignore
  sailbot.code-workspace
  src/integration_tests/README.md
  src/integration_tests/diagrams/src/structure.puml
  src/integration_tests/integration_tests/__init__.py
  src/integration_tests/integration_tests/integration_test_node.py
  src/integration_tests/package.xml
  src/integration_tests/resource/integration_tests
  src/integration_tests/setup.cfg
  src/integration_tests/setup.py
  src/integration_tests/testplans/example.yaml
Labels: infrastructure

#228 Added flask dependency to the container
  .devcontainer/Dockerfile
  .devcontainer/base-dev/base-dev.Dockerfile
Labels: dependencies

#229 Update setup_can script
  .devcontainer/deployment/helpers/setup_can.sh
Labels: enhancement, infrastructure
